CREATE TABLE IF NOT EXISTS orders (
    ID SERIAL PRIMARY KEY,
    userID INT NOT NULL,
    total INT NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);